name: Build Android Client

on:
  workflow_dispatch:
    inputs:
      release:
        description: 'Ready to release?'
        required: true
        default: 'no'
        type: choice
        options: [ "yes", "no" ]
        
      tag_name:
        description: 'Release tag (e.g., v1.0.0)'
        required: false
        default: 'v1.0.0'
        type: string
      changelog:
        description: 'Changelog for this release'
        required: false
        default: ''
        type: string

jobs:
  build-android:
    name: android_arm64
    runs-on: ubuntu-latest

    strategy:
      matrix:
        config:
        - name: "android_arm64"
          generator: "Unix Makefiles"
          target: traintastic-client
          jobs: 4
          build_type: Release
          defines: ""

    steps:

    - uses: FranzDiebold/github-env-vars-action@v2

    - name: Checkout
      uses: actions/checkout@v3
      with:
        submodules: recursive

    # Install Qt for Android
    - name: Install Qt 6.5 (Android)
      uses: jurplel/install-qt-action@v4
      with:
        cache: true
        version: 6.5.*
        target: android
        modules: qtwebsockets
        arch: android_arm64_v8a

    # Install Android SDK + NDK
    - name: Install Android SDK
      uses: android-actions/setup-android@v3

    - name: Install NDK 26
      run: sdkmanager "ndk;26.1.10909125"

    - name: Set NDK path
      run: echo "ANDROID_NDK_HOME=$ANDROID_SDK_ROOT/ndk/26.1.10909125" >> $GITHUB_ENV

    # Create Build Environment
    - name: Create Build Directory
      run: cmake -E make_directory ${{github.workspace}}/client/build

    # Configure CMake for Android
    - name: Configure CMake (Android)
      shell: bash
      working-directory: ${{github.workspace}}/client/build
      run: |
        cmake $GITHUB_WORKSPACE/client \
          -G "${{matrix.config.generator}}" \
          -DCMAKE_BUILD_TYPE=${{matrix.config.build_type}} \
          -DCMAKE_TOOLCHAIN_FILE=$ANDROID_NDK_HOME/build/cmake/android.toolchain.cmake \
          -DANDROID_ABI=arm64-v8a \
          -DANDROID_PLATFORM=28 \
          ${{matrix.config.defines}}

    # Build for Android
    - name: Build
      working-directory: ${{github.workspace}}/client/build
      shell: bash
      run: cmake --build . --config ${{matrix.config.build_type}} --target ${{matrix.config.target}} --parallel ${{matrix.config.jobs}}

    # Upload Android artifact
    - name: Upload Android Build
      uses: actions/upload-artifact@v4
      with:
        name: traintastic-client-android-arm64
        path: ${{github.workspace}}/client/build

